/*
 * Copyright (C) 2011 Dimas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * MainForm.java
 *
 * Created on Nov 21, 2011, 2:12:16 PM
 */
package sipus.ui;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import sipus.dao.AdminDao;
import sipus.dao.TransaksiPeminjamanDao;
import sipus.dao.svc.DaoService;
import sipus.model.Admin;
import sipus.model.TransaksiPeminjaman;
import sipus.swing.VerticalButtonUI;
import sipus.swing.ActiveFrame;
import sipus.util.OptionPane;

/**
 *
 * @author Dimas
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    private UILogin uiLogin = new UILogin(this, true);
    private int total;
    private int adminID;
    private AdminDao adminDao;
    private TransaksiPeminjamanDao peminjamanDao;

    public MainForm() {
        initComponents();
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        popUp = new javax.swing.JPopupMenu();
        panelPopUp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();
        applicationChooser = new sipus.swing.ApplicationChooser();
        jToolBar1 = new javax.swing.JToolBar();
        bAnggota = new javax.swing.JButton();
        bBuku = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bPeminjaman = new javax.swing.JButton();
        bPengembalian = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tTotal = new javax.swing.JFormattedTextField();
        desktop = new sipus.swing.DesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lDatabase = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lLogin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTime1 = new sipus.swing.JTime();
        panelDinas = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        bWindow = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mBuku = new javax.swing.JMenuItem();
        mAnggota = new javax.swing.JMenuItem();
        mKategori = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mPeminjaman = new javax.swing.JMenuItem();
        mPengembalian = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panelPopUp.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Active Windows");

        bClose.setText("x");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(bClose))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(bClose))
        );

        panelPopUp.add(jPanel2, java.awt.BorderLayout.PAGE_START);
        panelPopUp.add(applicationChooser, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Perpustakaan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/anggota.png"))); // NOI18N
        bAnggota.setText("Anggota");
        bAnggota.setFocusable(false);
        bAnggota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAnggota.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnggotaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAnggota);

        bBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/buku.png"))); // NOI18N
        bBuku.setText("Buku");
        bBuku.setFocusable(false);
        bBuku.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuku.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBukuActionPerformed(evt);
            }
        });
        jToolBar1.add(bBuku);
        jToolBar1.add(jSeparator1);

        bPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/peminjaman.PNG"))); // NOI18N
        bPeminjaman.setText("Peminjaman");
        bPeminjaman.setFocusable(false);
        bPeminjaman.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPeminjaman.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPeminjamanActionPerformed(evt);
            }
        });
        jToolBar1.add(bPeminjaman);

        bPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/pengembalian.PNG"))); // NOI18N
        bPengembalian.setText("Pengembalian");
        bPengembalian.setFocusable(false);
        bPengembalian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPengembalian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPengembalianActionPerformed(evt);
            }
        });
        jToolBar1.add(bPengembalian);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        tTotal.setBackground(new java.awt.Color(0, 0, 0));
        tTotal.setEditable(false);
        tTotal.setForeground(new java.awt.Color(0, 255, 0));
        tTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tTotal.setFont(new java.awt.Font("Courier New", 1, 48));
        tTotal.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel1.add(tTotal, java.awt.BorderLayout.EAST);

        jToolBar1.add(jPanel1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/db.png"))); // NOI18N
        jLabel3.setText("Connection : ");

        lDatabase.setText("DISCONNECT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDatabase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(lDatabase))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/user_status.png"))); // NOI18N
        jLabel1.setText("User :");

        lLogin.setText("NOT LOGIN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lLogin))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelDinas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelDinas.setLayout(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDinas, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(panelDinas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);
        jToolBar2.setOpaque(false);

        bWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/frame.png"))); // NOI18N
        bWindow.setText("Windows ");
        bWindow.setFocusable(false);
        bWindow.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bWindow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWindowActionPerformed(evt);
            }
        });
        jToolBar2.add(bWindow);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("File");

        jMenuItem4.setText("Data Perusahaan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Backup Data");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Restore Data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        mBuku.setText("Buku");
        mBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBukuActionPerformed(evt);
            }
        });
        jMenu2.add(mBuku);

        mAnggota.setText("Anggota");
        mAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnggotaActionPerformed(evt);
            }
        });
        jMenu2.add(mAnggota);

        mKategori.setText("Kategori Buku");
        mKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKategoriActionPerformed(evt);
            }
        });
        jMenu2.add(mKategori);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        mPeminjaman.setText("Peminjaman");
        mPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPeminjamanActionPerformed(evt);
            }
        });
        jMenu3.add(mPeminjaman);

        mPengembalian.setText("Pengembalian");
        mPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPengembalianActionPerformed(evt);
            }
        });
        jMenu3.add(mPengembalian);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("History");

        jMenuItem6.setText("Peminjaman");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Laporan");

        jMenuItem8.setText("Peminjaman");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem7.setText("History Peminjaman");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Pengaturan");

        jMenuItem9.setText("Database");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBukuActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIBuku uiBuku = new UIBuku();
        final ActiveFrame af = new ActiveFrame(uiBuku);
        listActiveFrame(af);

        uiBuku.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });

        desktop.add(uiBuku);
        desktop.getDesktopManager().maximizeFrame(uiBuku);
        uiBuku.setVisible(true);
        tTotal.setVisible(false);
        uiBuku.setMainForm(this);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bBukuActionPerformed

    private void mKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKategoriActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIKategori uIKategori = new UIKategori();
        final ActiveFrame af = new ActiveFrame(uIKategori);
        listActiveFrame(af);

        uIKategori.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIKategori);
        uIKategori.setSize(new Dimension(600, desktop.getHeight()));
        uIKategori.setVisible(true);
        tTotal.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_mKategoriActionPerformed

    private void bAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnggotaActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIAnggota uiAnggota = new UIAnggota();
        final ActiveFrame af = new ActiveFrame(uiAnggota);
        listActiveFrame(af);

        uiAnggota.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });

        desktop.add(uiAnggota);
        desktop.getDesktopManager().maximizeFrame(uiAnggota);
        uiAnggota.setVisible(true);
        tTotal.setVisible(false);


        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bAnggotaActionPerformed

    private void mPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPeminjamanActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIPeminjaman uIPeminjaman = new UIPeminjaman();
        final ActiveFrame af = new ActiveFrame(uIPeminjaman);
        listActiveFrame(af);

        uIPeminjaman.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIPeminjaman);
        desktop.getDesktopManager().maximizeFrame(uIPeminjaman);
        uIPeminjaman.setVisible(true);
        tTotal.setVisible(false);
        uIPeminjaman.setMainForm(this);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));;
    }//GEN-LAST:event_mPeminjamanActionPerformed

    private void bPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPeminjamanActionPerformed
        // TODO add your handling code here:
        mPeminjamanActionPerformed(evt);
    }//GEN-LAST:event_bPeminjamanActionPerformed

    private void bPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPengembalianActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIPengembalian uIPengembalian = new UIPengembalian();
        final ActiveFrame af = new ActiveFrame(uIPengembalian);
        listActiveFrame(af);

        uIPengembalian.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIPengembalian);
        desktop.getDesktopManager().maximizeFrame(uIPengembalian);
        uIPengembalian.setVisible(true);
        tTotal.setVisible(false);
        uIPengembalian.setMainForm(this);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bPengembalianActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (adminDao == null) {
            adminDao = DaoService.getAdminDao();
        }
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        Admin admin = new Admin();
        admin.setId(adminID);
        admin.setStatus(0);
        adminDao.updateStatus(admin);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIHistoryPeminjaman uIHistoryPeminjaman = new UIHistoryPeminjaman();
        final ActiveFrame af = new ActiveFrame(uIHistoryPeminjaman);
        listActiveFrame(af);

        uIHistoryPeminjaman.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIHistoryPeminjaman);
        desktop.getDesktopManager().maximizeFrame(uIHistoryPeminjaman);
        uIHistoryPeminjaman.setVisible(true);
        tTotal.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIDataPerusahaan uIDataPerusahaan = new UIDataPerusahaan();
        final ActiveFrame af = new ActiveFrame(uIDataPerusahaan);
        listActiveFrame(af);

        uIDataPerusahaan.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIDataPerusahaan);
        uIDataPerusahaan.setVisible(true);
        tTotal.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIPeminjamanPeriode uiPeminjamanRep = new UIPeminjamanPeriode();
        final ActiveFrame af = new ActiveFrame(uiPeminjamanRep);
        listActiveFrame(af);

        uiPeminjamanRep.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uiPeminjamanRep);
        uiPeminjamanRep.setVisible(true);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        cetakHistoryPeminjaman();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIDatabase uIDatabase = new UIDatabase();
        final ActiveFrame af = new ActiveFrame(uIDatabase);
        listActiveFrame(af);

        uIDatabase.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIDatabase);
        uIDatabase.setVisible(true);
        tTotal.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIBackup uIBackup = new UIBackup();
        final ActiveFrame af = new ActiveFrame(uIBackup);
        listActiveFrame(af);

        uIBackup.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIBackup);
        uIBackup.setVisible(true);
        tTotal.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UIRestore uIRestore = new UIRestore();
        final ActiveFrame af = new ActiveFrame(uIRestore);
        listActiveFrame(af);

        uIRestore.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                setActiveFrame(af);
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                removeListActiveFrame(af);
            }
        });
        desktop.add(uIRestore);
        uIRestore.setVisible(true);
        tTotal.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        if (adminDao == null) {
            adminDao = DaoService.getAdminDao();
        }
        if (OptionPane.showConfirmMessage("Yakin logout?") == JOptionPane.YES_OPTION) {
            Admin admin = new Admin();
            admin.setId(adminID);
            admin.setStatus(0);
            adminDao.updateStatus(admin);
            desktop.removeAll();
            uiLogin.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (adminDao == null) {
            adminDao = DaoService.getAdminDao();
        }
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        Admin admin = new Admin();
        admin.setId(adminID);
        admin.setStatus(0);
        adminDao.updateStatus(admin);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBukuActionPerformed
        // TODO add your handling code here:
        bBukuActionPerformed(evt);
    }//GEN-LAST:event_mBukuActionPerformed

    private void mAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnggotaActionPerformed
        // TODO add your handling code here:
        bAnggotaActionPerformed(evt);
    }//GEN-LAST:event_mAnggotaActionPerformed

    private void mPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPengembalianActionPerformed
        // TODO add your handling code here:
        bPengembalianActionPerformed(evt);
    }//GEN-LAST:event_mPengembalianActionPerformed

    private void bWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWindowActionPerformed
        // TODO add your handling code here:        
        popUp.setPreferredSize(new Dimension(200, jToolBar2.getHeight()));
        popUp.setLocation(jToolBar2.getWidth(), 115);
        if (bWindow.isSelected()) {
            popUp.setVisible(true);
        } else {
            popUp.setVisible(false);
        }
    }//GEN-LAST:event_bWindowActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        // TODO add your handling code here:
        popUp.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sipus.swing.ApplicationChooser applicationChooser;
    private javax.swing.JButton bAnggota;
    private javax.swing.JButton bBuku;
    private javax.swing.JButton bClose;
    private javax.swing.JButton bPeminjaman;
    private javax.swing.JButton bPengembalian;
    private javax.swing.JToggleButton bWindow;
    private sipus.swing.DesktopPane desktop;
    private javax.swing.JDialog dialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private sipus.swing.JTime jTime1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lDatabase;
    private javax.swing.JLabel lLogin;
    private javax.swing.JMenuItem mAnggota;
    private javax.swing.JMenuItem mBuku;
    private javax.swing.JMenuItem mKategori;
    private javax.swing.JMenuItem mPeminjaman;
    private javax.swing.JMenuItem mPengembalian;
    private javax.swing.JPanel panelDinas;
    private javax.swing.JPanel panelPopUp;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JFormattedTextField tTotal;
    // End of variables declaration//GEN-END:variables

    private void initForm() {

        setIconImage(new ImageIcon(getClass().getResource("/sipus/icon/icon.png")).getImage());
        setExtendedState(MAXIMIZED_BOTH);

        uiLogin.setMainForm(this);
        tTotal.setVisible(false);

        applicationChooser.setDesktopPane(desktop);
        bWindow.setUI(new VerticalButtonUI(270));
        popUp.add(panelPopUp);
    }

    public void setConnectionText(String text) {
        lDatabase.setText(text);
    }

    public void showKategori(ActionEvent evt) {
        mKategoriActionPerformed(evt);
    }

    public void showTransaksiPeminjaman() {
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        UITransaksiPeminjaman uITransaksiPeminjaman = new UITransaksiPeminjaman();
        desktop.add(uITransaksiPeminjaman);
        desktop.getDesktopManager().maximizeFrame(uITransaksiPeminjaman);
        uITransaksiPeminjaman.setVisible(true);
        tTotal.setVisible(true);
        uITransaksiPeminjaman.setMainForm(this);
        uITransaksiPeminjaman.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                tTotal.setVisible(false);
            }
        });
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    public void reloadUIPeminjaman() {
//        uiPeminjaman.reload();
    }

    public void reloadUIPengembalian() {
//        uiPengembalian.reload();
    }

    public void listActiveFrame(ActiveFrame o) {
        applicationChooser.addListElement(o);
    }

    public void removeListActiveFrame(ActiveFrame o) {
        applicationChooser.removeListElement(o);
    }

    public void setActiveFrame(ActiveFrame o) {
        applicationChooser.setSelectedObject(o);
    }

    public int getTotal() {
        return total;
    }

    public void setTotal(int total) {
        this.total = total;
        tTotal.setValue(total);
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        uiLogin.setVisible(b);
    }

    public void setAdmin(int id, String username) {
        adminID = id;
        lLogin.setText(username.toUpperCase());
    }

    private JasperPrint getJasperPrint(String file) {
        if (peminjamanDao == null) {
            peminjamanDao = DaoService.getTransaksiPeminjamanDao();
        }
        JasperPrint jasperPrint = null;
        try {
            List<TransaksiPeminjaman> list = peminjamanDao.getAllPrint();

            JasperReport jasperReport = JasperCompileManager.compileReport("report/" + file + ".jrxml");
            JRDataSource dataSource = new JRBeanCollectionDataSource(list);
            Map<Object, Object> map = new HashMap<Object, Object>();
            map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
            jasperPrint = JasperFillManager.fillReport(jasperReport, map);
        } catch (JRException ex) {
            OptionPane.showErrorMessage(ex);
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return jasperPrint;
    }

    private void cetakHistoryPeminjaman() {
        try {
            if (peminjamanDao == null) {
                peminjamanDao = DaoService.getTransaksiPeminjamanDao();
            }
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            List<TransaksiPeminjaman> list = peminjamanDao.getAllHistoryPrint();

            JasperReport jasperReport = JasperCompileManager.compileReport("report/HistoryPeminjaman.jrxml");
            JRDataSource dataSource = new JRBeanCollectionDataSource(list);
            Map<Object, Object> map = new HashMap<Object, Object>();
            map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map);
            JasperViewer.viewReport(jasperPrint, false);
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            OptionPane.showErrorMessage(ex);
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
