/*
 * Copyright (C) 2011 Dimas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * UIBuku.java
 *
 * Created on Nov 24, 2011, 10:23:25 PM
 */
package sipus.ui;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sipus.dao.BukuDao;
import sipus.dao.KategoriDao;
import sipus.dao.svc.DaoService;
import sipus.model.Buku;
import sipus.model.Kategori;
import sipus.swing.MyTable;
import sipus.table.TableModelBuku;
import sipus.table.render.StockTableRenderer;
import sipus.util.OptionPane;

/**
 *
 * @author Dimas
 */
public class UIBuku extends javax.swing.JInternalFrame {

    /** Creates new form UIBuku */
    private TableModelBuku modelBuku = new TableModelBuku();
    private int col[] = {60, 100, 300, 200, 150, 150, 150, 150, 100, 150}, action = 0;
    private static final int TAMBAH = 1, UBAH = 2;
    private MyTable myTable = new MyTable(modelBuku, col);
    private BukuDao bukuDao;
    private KategoriDao kategoriDao;
    private MainForm mainForm;
    private Timer timer;

    public UIBuku() {
        initComponents();
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tHargaSewa = new javax.swing.JFormattedTextField();
        tKode = new javax.swing.JTextField();
        tJudul = new javax.swing.JTextField();
        tPenulis = new javax.swing.JTextField();
        tPenerbit = new javax.swing.JTextField();
        tISBN = new javax.swing.JTextField();
        cboKategori = new javax.swing.JComboBox();
        tDenda = new javax.swing.JFormattedTextField();
        bKategori = new javax.swing.JButton();
        tStok = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bBatal = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReload = new javax.swing.JButton();

        dialog.setTitle("Data Buku");
        dialog.setModal(true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dialogWindowActivated(evt);
            }
        });

        jLabel1.setText("Kode Buku");

        jLabel2.setText("Judul Buku");

        jLabel3.setText("Penulis");

        jLabel4.setText("Penerbit");

        jLabel5.setText("Kategori");

        jLabel6.setText("ISBN");

        jLabel7.setText("Harga Sewa");

        jLabel8.setText("Denda");

        tHargaSewa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        cboKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKategori.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cboKategoriPopupMenuWillBecomeVisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        tDenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tDenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tDendaKeyPressed(evt);
            }
        });

        bKategori.setText("...");
        bKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKategoriActionPerformed(evt);
            }
        });

        tStok.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tStokKeyPressed(evt);
            }
        });

        jLabel9.setText("Stok");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addComponent(tJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(tPenulis, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(tPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tHargaSewa, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(tKode, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cboKategori, 0, 261, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55)
                        .addComponent(tStok, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(45, 45, 45)
                        .addComponent(tDenda, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bKategori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        bBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/cancel.png"))); // NOI18N
        bBatal.setText("Batal");
        bBatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBatal.setPreferredSize(new java.awt.Dimension(67, 45));
        bBatal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/save.png"))); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(bSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog.getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Buku");

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/new.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/edit.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/delete.png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/reload.png"))); // NOI18N
        bReload.setText("Reload");
        bReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(bReload)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(bUbah)
                    .addComponent(bHapus)
                    .addComponent(bReload))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        setAction(TAMBAH);
        clearForm();
        dialog.setVisible(true);
    }//GEN-LAST:event_bTambahActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        if (getAction() == TAMBAH) {
            simpan();
        } else if (getAction() == UBAH) {
            ubah(myTable.getSelectedRow());
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        if (myTable.getSelectedRow() < 0) {
            OptionPane.showWarningMessage("Silakan pilih data yang akan diubah");
        } else {
            setAction(UBAH);
            loadTableToForm(myTable.getSelectedRow());
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        if (myTable.getSelectedRow() < 0) {
            OptionPane.showWarningMessage("Silakan pilih data yang akan dihapus");
        } else {
            if (OptionPane.showQuestionBox("Yakin menghapus data?", new String[]{"Hapus", "Batal"}) == JOptionPane.YES_OPTION) {
                hapus(myTable.getSelectedRow());
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // TODO add your handling code here:
        dialog.dispose();
    }//GEN-LAST:event_bBatalActionPerformed

    private void tDendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDendaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            bSimpan.requestFocus();
        }
    }//GEN-LAST:event_tDendaKeyPressed

    private void bKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKategoriActionPerformed
        // TODO add your handling code here:
        getMainForm().showKategori(evt);
    }//GEN-LAST:event_bKategoriActionPerformed

    private void cboKategoriPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboKategoriPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        reloadKategori();
    }//GEN-LAST:event_cboKategoriPopupMenuWillBecomeVisible

    private void bReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReloadActionPerformed
        // TODO add your handling code here:
        reloadTable();
}//GEN-LAST:event_bReloadActionPerformed

    private void tStokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tStokKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tStokKeyPressed

    private void dialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogWindowActivated
        // TODO add your handling code here:
        tJudul.requestFocus();
    }//GEN-LAST:event_dialogWindowActivated
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKategori;
    private javax.swing.JButton bReload;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox cboKategori;
    private javax.swing.JDialog dialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField tDenda;
    private javax.swing.JFormattedTextField tHargaSewa;
    private javax.swing.JTextField tISBN;
    private javax.swing.JTextField tJudul;
    private javax.swing.JTextField tKode;
    private javax.swing.JTextField tPenerbit;
    private javax.swing.JTextField tPenulis;
    private javax.swing.JFormattedTextField tStok;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        bukuDao = DaoService.getBukuDao();
        kategoriDao = DaoService.getKategoriDao();

        jScrollPane1.setViewportView(myTable);

        dialog.pack();
        dialog.setLocationRelativeTo(null);

        reloadKategori();
        reloadTable();
        initTableCellRenderer();
    }

    private void clearForm() {
        tKode.setText(bukuDao.getGeneratedNumber());
        tJudul.setText("");
        tPenulis.setText("");
        tPenerbit.setText("");
        cboKategori.setSelectedIndex(-1);
        tISBN.setText("");
        tHargaSewa.setText("");
        tDenda.setText("");
        tStok.setText("");
        tJudul.requestFocus();
    }

    private void simpan() {
        Buku buku = getBuku();
        bukuDao.insert(buku);

        if (bukuDao.isSuccess()) {
            String kategori = cboKategori.getSelectedItem().toString();
            buku.setKategori(kategori.substring(7, kategori.length()));
            buku.setHargaSewa(Integer.parseInt(tHargaSewa.getValue().toString()));
            buku.setDenda(Integer.parseInt(tDenda.getValue().toString()));

            modelBuku.insert(buku);
            clearForm();
        }
    }

    private void ubah(int selectedROw) {
        Buku buku = getBuku();
        bukuDao.update(buku);

        if (bukuDao.isSuccess()) {
            String kategori = cboKategori.getSelectedItem().toString();
            buku.setKategori(kategori.substring(7, kategori.length()));
            buku.setHargaSewa(Integer.parseInt(tHargaSewa.getValue().toString()));
            buku.setDenda(Integer.parseInt(tDenda.getValue().toString()));

            modelBuku.update(selectedROw, buku);
            clearForm();
            dialog.dispose();
        }
    }

    private void hapus(int selectedRow) {
        Buku buku = new Buku();
        buku.setKode(myTable.getValueAt(selectedRow, 1).toString());
        bukuDao.delete(buku);
        if (bukuDao.isSuccess()) {
            modelBuku.delete(selectedRow);
        }
    }

    private void loadTableToForm(int selectedRow) {
        tKode.setText(myTable.getValueAt(selectedRow, 1).toString());
        tJudul.setText(myTable.getValueAt(selectedRow, 2).toString());
        tPenulis.setText(myTable.getValueAt(selectedRow, 3).toString());
        tPenerbit.setText(myTable.getValueAt(selectedRow, 4).toString());

        String kategori = myTable.getValueAt(selectedRow, 5).toString();
        cboKategori.setSelectedItem(getKategori(kategori));

        tISBN.setText(myTable.getValueAt(selectedRow, 6).toString());
        int hargaSewa = Integer.parseInt(myTable.getValueAt(selectedRow, 7).toString());
        tHargaSewa.setValue(hargaSewa);
        tStok.setText(myTable.getValueAt(selectedRow, 8).toString());
        int denda = Integer.parseInt(myTable.getValueAt(selectedRow, 9).toString());
        tDenda.setValue(denda);

        tJudul.requestFocus();
    }

    private Buku getBuku() {
        Buku buku = new Buku();
        buku.setKode(tKode.getText());
        buku.setJudul(tJudul.getText());
        buku.setPenulis(tPenulis.getText());
        buku.setPenerbit(tPenerbit.getText());
        buku.setStok(Integer.parseInt(tStok.getText()));

        String kategori = cboKategori.getSelectedItem().toString().substring(0, 4);

        buku.setKategori(kategori);
        buku.setIsbn(tISBN.getText());

        int hargaSewa = Integer.parseInt(tHargaSewa.getValue().toString());
        int denda = Integer.parseInt(tDenda.getValue().toString());

        buku.setHargaSewa(hargaSewa);
        buku.setDenda(denda);
        if (getAction() == UBAH) {
            buku.setOldKode(modelBuku.getValueAt(myTable.getSelectedRow(), 1).toString());
        }
        return buku;
    }

    private void reloadTable() {
        for (int i = myTable.getRowCount() - 1; i >= 0; i--) {
            modelBuku.delete(i);
        }
        List<Buku> list = bukuDao.getAll();
        for (Buku buku : list) {
            buku.setKode(buku.getKode());
            buku.setJudul(buku.getJudul());
            buku.setPenulis(buku.getPenulis());
            buku.setPenerbit(buku.getPenerbit());
            buku.setKategori(buku.getKategori());
            buku.setIsbn(buku.getIsbn());
            buku.setHargaSewa(buku.getHargaSewa());
            buku.setDenda(buku.getDenda());
            modelBuku.insert(buku);
        }
    }

    private void reloadKategori() {
        cboKategori.removeAllItems();
        List<Kategori> list = kategoriDao.getAll();
        for (Kategori kategori : list) {
            kategori.setKode(kategori.getKode());
            kategori.setKategori(kategori.getKategori());
            String ctg = kategori.getKode() + " | " + kategori.getKategori();
            cboKategori.addItem(ctg);
        }
    }

    private String getKategori(String kat) {
        Kategori kategori = kategoriDao.getKategori(kat);
        String kode = kategori.getKode();
        return kode + " | " + kat;
    }

    public int getAction() {
        return action;
    }

    public void setAction(int action) {
        this.action = action;
    }

    public MainForm getMainForm() {
        return mainForm;
    }

    public void setMainForm(MainForm mainForm) {
        this.mainForm = mainForm;
    }

    private void initTableCellRenderer() {
        for (int i = 1; i < myTable.getColumnCount(); i++) {
            myTable.getColumnModel().getColumn(i).setCellRenderer(new StockTableRenderer());
        }
    }
}
