/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIDataPerusahaan.java
 *
 * Created on Dec 14, 2011, 5:37:34 PM
 */
package sipus.ui;

import java.awt.event.KeyEvent;
import sipus.dao.DataPerusahaanDao;
import sipus.dao.svc.DaoService;
import sipus.model.DataPerusahaan;
import sipus.util.OptionPane;

/**
 *
 * @author Administrator
 */
public class UIDataPerusahaan extends javax.swing.JInternalFrame {

    /** Creates new form UIDataPerusahaan */
    private DataPerusahaanDao dataPerusahaanDao;

    public UIDataPerusahaan() {
        initComponents();
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tNoTelp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bBatal = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Perusahaan");

        jLabel1.setText("Nama Perusahaan");

        jLabel2.setText("Alamat");

        tNoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNoTelpKeyPressed(evt);
            }
        });

        jLabel3.setText("No. Telp");

        bBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/cancel.png"))); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/save.png"))); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNoTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(tAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(tNama, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBatal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBatal)
                    .addComponent(bSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        DataPerusahaan dataPerusahaan = new DataPerusahaan();
        dataPerusahaan.setNama(tNama.getText());
        dataPerusahaan.setAlamat(tAlamat.getText());
        dataPerusahaan.setNoTelp(tNoTelp.getText());
        if (dataPerusahaanDao.isExists()) {
            dataPerusahaanDao.update(dataPerusahaan);
        } else {
            dataPerusahaanDao.insert(dataPerusahaan);
        }
        if (dataPerusahaanDao.isSuccess()) {
            OptionPane.showMessage("Data Perusahaan berhasil disimpan");
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bBatalActionPerformed

    private void tNoTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNoTelpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            bSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_tNoTelpKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNoTelp;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        pack();
        dataPerusahaanDao = DaoService.getDataPerusahaanDao();
        reload();
    }

    private void reload() {
        DataPerusahaan dataPerusahaan = dataPerusahaanDao.getDataPerusahaan();
        tNama.setText(dataPerusahaan.getNama());
        tAlamat.setText(dataPerusahaan.getAlamat());
        tNoTelp.setText(dataPerusahaan.getNoTelp());
    }
}
