/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UILogin.java
 *
 * Created on Dec 12, 2011, 2:37:20 PM
 */
package sipus.ui;

import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import oracle.jdbc.pool.OracleDataSource;
import sipus.dao.AdminDao;
import sipus.dao.svc.DaoService;
import sipus.model.Admin;
import sipus.util.OptionPane;
import sipus.util.Restore;

/**
 *
 * @author Administrator
 */
public class UILogin extends javax.swing.JDialog {

    /** Creates new form UILogin */
    private AdminDao adminDao;
    private MainForm mainForm;
    private String username;
    private String password;

    public UILogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        titlePanel1 = new sipus.swing.TitlePanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        bUserLogin = new sipus.swing.LinkButton();
        bPanelRestore = new sipus.swing.LinkButton();
        bPanelRestore1 = new sipus.swing.LinkButton();
        pCard = new javax.swing.JPanel();
        pLogin = new sipus.swing.PanelCard();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        tPass = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        pRestore = new sipus.swing.PanelCard();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tFile = new javax.swing.JTextField();
        bFile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        bRestore = new javax.swing.JButton();
        pKonfigurasi = new sipus.swing.PanelCard();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tServerC = new javax.swing.JTextField();
        tPasswordC = new javax.swing.JPasswordField();
        bSimpan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tPortC = new javax.swing.JTextField();
        tUsernameC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("User Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout titlePanel1Layout = new javax.swing.GroupLayout(titlePanel1);
        titlePanel1.setLayout(titlePanel1Layout);
        titlePanel1Layout.setHorizontalGroup(
            titlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        titlePanel1Layout.setVerticalGroup(
            titlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        jPanel2.add(titlePanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        bUserLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/user_login.png"))); // NOI18N
        bUserLogin.setText("User Login");
        bUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserLoginActionPerformed(evt);
            }
        });

        bPanelRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/restore_db.png"))); // NOI18N
        bPanelRestore.setText("Restore");
        bPanelRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanelRestoreActionPerformed(evt);
            }
        });

        bPanelRestore1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/create_db.png"))); // NOI18N
        bPanelRestore1.setText("Konfigurasi");
        bPanelRestore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPanelRestore1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPanelRestore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPanelRestore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPanelRestore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPanelRestore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel4);

        pCard.setLayout(new java.awt.CardLayout());

        pLogin.setTitle("User Login");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/userlogin.png"))); // NOI18N

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        tPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tPassKeyPressed(evt);
            }
        });

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tPass, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(tUser, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                    .addComponent(bLogin))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLogin))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 258;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 0, 53, 0);
        pLogin.add(jPanel3, gridBagConstraints);

        pCard.add(pLogin, "User Login");

        pRestore.setMaximumSize(new java.awt.Dimension(450, 203));
        pRestore.setPreferredSize(new java.awt.Dimension(450, 203));
        pRestore.setTitle("Restore Database");

        jLabel4.setText("File database");

        tFile.setEditable(false);

        bFile.setText("...");
        bFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFileActionPerformed(evt);
            }
        });

        jLabel5.setText("Username yang dituju");

        jLabel6.setText("Password yang dituju");

        bRestore.setText("Restore");
        bRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRestoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bRestore)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(tUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(tFile, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRestore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 248;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 68, 32, 90);
        pRestore.add(jPanel7, gridBagConstraints);

        pCard.add(pRestore, "Restore");

        pKonfigurasi.setMaximumSize(new java.awt.Dimension(450, 203));
        pKonfigurasi.setPreferredSize(new java.awt.Dimension(450, 203));
        pKonfigurasi.setTitle("Restore Database");

        jLabel8.setText("Server");

        jLabel9.setText("Password");

        tServerC.setText("localhost");

        bSimpan.setText("Simpan Konfigurasi");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        jLabel10.setText("Port");

        tPortC.setText("1521");

        jLabel11.setText("Username");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSimpan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tServerC, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(tPortC, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(tUsernameC, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(tPasswordC, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tServerC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tPortC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tUsernameC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tPasswordC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 248;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 68, 32, 90);
        pKonfigurasi.add(jPanel8, gridBagConstraints);

        pCard.add(pKonfigurasi, "Konfigurasi");

        jSplitPane1.setRightComponent(pCard);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:        
        login();
    }//GEN-LAST:event_bLoginActionPerformed

    private void tPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_tPassKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tUser.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (OptionPane.showConfirmMessage("Yakin keluar aplikasi?") == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void bUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserLoginActionPerformed
        // TODO add your handling code here:
        ((CardLayout) pCard.getLayout()).show(pCard, "User Login");
    }//GEN-LAST:event_bUserLoginActionPerformed

    private void bPanelRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanelRestoreActionPerformed
        // TODO add your handling code here:
        ((CardLayout) pCard.getLayout()).show(pCard, "Restore");
    }//GEN-LAST:event_bPanelRestoreActionPerformed

    private void bFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Oracle Database", "dmp");
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            tFile.setText(chooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_bFileActionPerformed

    private void bRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRestoreActionPerformed
        // TODO add your handling code here:
        username = tUsername.getText();
        password = String.valueOf(tPassword.getPassword(), 0, tPassword.getPassword().length);
        if (tFile.getText().length() == 0) {
            OptionPane.showWarningMessage("Silakan pilih file penyimpanan");
        } else {
            if (isConnectionSuccess(username, password)) {
                setCursor(new Cursor(Cursor.WAIT_CURSOR));
                Restore restore = new Restore(tFile.getText());
                restore.setFromuser("dimas");
                restore.setUsername(username);
                restore.setPassword(password);
                restore.startRestore();
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        }
    }//GEN-LAST:event_bRestoreActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        username = tUsernameC.getText();
        password = String.valueOf(tPasswordC.getPassword(), 0, tPasswordC.getPassword().length);
        if (isConnectionSuccess(username, password)) {
            simpan();
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bPanelRestore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPanelRestore1ActionPerformed
        // TODO add your handling code here:
        ((CardLayout) pCard.getLayout()).show(pCard, "Konfigurasi");
    }//GEN-LAST:event_bPanelRestore1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFile;
    private javax.swing.JButton bLogin;
    private sipus.swing.LinkButton bPanelRestore;
    private sipus.swing.LinkButton bPanelRestore1;
    private javax.swing.JButton bRestore;
    private javax.swing.JButton bSimpan;
    private sipus.swing.LinkButton bUserLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pCard;
    private sipus.swing.PanelCard pKonfigurasi;
    private sipus.swing.PanelCard pLogin;
    private sipus.swing.PanelCard pRestore;
    private javax.swing.JTextField tFile;
    private javax.swing.JPasswordField tPass;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JPasswordField tPasswordC;
    private javax.swing.JTextField tPortC;
    private javax.swing.JTextField tServerC;
    private javax.swing.JTextField tUser;
    private javax.swing.JTextField tUsername;
    private javax.swing.JTextField tUsernameC;
    private sipus.swing.TitlePanel titlePanel1;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        setSize(new Dimension(600, getHeight()));
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/sipus/icon/userlogin.png")).getImage());
    }

    private void login() {
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if (adminDao == null) {
            adminDao = DaoService.getAdminDao();
        }
        String usernameL = tUser.getText();
        String passwordL = String.valueOf(tPass.getPassword(), 0, tPass.getPassword().length);
        Admin admin = adminDao.getAdmin(usernameL, passwordL);
        if (admin == null) {
            OptionPane.showWarningMessage("Login Gagal");
            clearForm();
        } else {
            if (admin.getStatus() == 1) {
                OptionPane.showWarningMessage("Anda sudah login");
            } else {
                dispose();
                admin.setId(admin.getId());
                admin.setStatus(1);
                adminDao.updateStatus(admin);
                mainForm.setAdmin(admin.getId(), admin.getUsername());
                mainForm.setConnectionText(DaoService.getConnection().toString());
                clearForm();
            }
        }
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void clearForm() {
        tUser.setText("");
        tPass.setText("");
        tUser.requestFocus();
    }

    public void setMainForm(MainForm mainForm) {
        this.mainForm = mainForm;
    }

    private boolean isConnectionSuccess(String username, String password) {
        boolean conn = false;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            OracleDataSource oracleDataSource = new OracleDataSource();
            oracleDataSource.setURL("jdbc:oracle:thin:@localhost:1521:XE");
            oracleDataSource.setUser(username);
            oracleDataSource.setPassword(password);
            Connection connection = oracleDataSource.getConnection();
            conn = true;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UIDatabase.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            conn = false;
            OptionPane.showErrorMessage("Koneksi Gagal : \n" + ex);
            Logger.getLogger(UIDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
        return conn;
    }

    private void simpan() {
        try {
            Properties properties = new Properties();
            properties.setProperty("Server", tServerC.getText());
            properties.setProperty("Port", tPortC.getText());
            properties.setProperty("Username", tUsernameC.getText());
            properties.setProperty("Password", String.valueOf(tPasswordC.getPassword(), 0, tPasswordC.getPassword().length));
            properties.store(new FileOutputStream("config/database.ini"), "Database Configuration");
            OptionPane.showMessage("Pengaturan database berhasil disimpan");
        } catch (IOException ex) {
            OptionPane.showErrorMessage(ex);
            Logger.getLogger(UIDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
