/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIPeminjamanRep.java
 *
 * Created on Dec 14, 2011, 8:19:50 PM
 */
package sipus.ui;

import java.awt.Cursor;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import sipus.dao.TransaksiPeminjamanDao;
import sipus.dao.svc.DaoService;
import sipus.model.TransaksiPeminjaman;
import sipus.util.OptionPane;

/**
 *
 * @author Administrator
 */
public class UIPeminjamanPeriode extends javax.swing.JInternalFrame {

    /** Creates new form UIPeminjamanRep */
    private TransaksiPeminjamanDao peminjamanDao;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public UIPeminjamanPeriode() {
        initComponents();
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bSemua = new javax.swing.JButton();
        bSesuai = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tglPinjam1 = new com.toedter.calendar.JDateChooser();
        tglPinjam2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laporan Peminjaman Periode");

        bSemua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/print.png"))); // NOI18N
        bSemua.setText("<html>Semua<br>Periode</html>");
        bSemua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSemua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSemuaActionPerformed(evt);
            }
        });
        jPanel2.add(bSemua);

        bSesuai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/print.png"))); // NOI18N
        bSesuai.setText("<html>Sesuai <br>Periode</html>");
        bSesuai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSesuai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSesuai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSesuaiActionPerformed(evt);
            }
        });
        jPanel2.add(bSesuai);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel2.setText("s/d");

        jLabel1.setText("Periode Laporan Peminjaman : ");

        tglPinjam1.setDateFormatString("dd MMMM yyyy");

        tglPinjam2.setDateFormatString("dd MMMM yyyy");

        jLabel3.setText("Mulai tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglPinjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglPinjam2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tglPinjam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglPinjam1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSemuaActionPerformed
        // TODO add your handling code here:
        cetakSemua("Peminjaman");
    }//GEN-LAST:event_bSemuaActionPerformed

    private void bSesuaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSesuaiActionPerformed
        // TODO add your handling code here:        
        try {
            cetak(tglPinjam1.getDate(), tglPinjam2.getDate());
        } catch (NullPointerException ex) {
            OptionPane.showErrorMessage("Silakan pilih periode");
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_bSesuaiActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSemua;
    private javax.swing.JButton bSesuai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser tglPinjam1;
    private com.toedter.calendar.JDateChooser tglPinjam2;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        peminjamanDao = DaoService.getTransaksiPeminjamanDao();
        pack();
    }

    private void cetakSemua(String file) {
        try {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            List<TransaksiPeminjaman> list = peminjamanDao.getAllPrint();

            JasperReport jasperReport = JasperCompileManager.compileReport("report/" + file + ".jrxml");
            JRDataSource dataSource = new JRBeanCollectionDataSource(list);
            Map<Object, Object> map = new HashMap<Object, Object>();
            map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map);
            JasperViewer.viewReport(jasperPrint, false);
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            OptionPane.showErrorMessage(ex);
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cetak(java.util.Date tgl1, java.util.Date tgl2) {
        try {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            Date date1 = Date.valueOf(dateFormat.format(tgl1));
            Date date2 = Date.valueOf(dateFormat.format(tgl2));
            List<TransaksiPeminjaman> list = peminjamanDao.getAllPrint(date1, date2);

            JasperReport jasperReport = JasperCompileManager.compileReport("report/PeminjamanPeriode.jrxml");
            JRDataSource dataSource = new JRBeanCollectionDataSource(list);
            Map<Object, Object> map = new HashMap<Object, Object>();
            map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map);
            JasperViewer.viewReport(jasperPrint, false);
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            OptionPane.showErrorMessage(ex);
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
