/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIPeminjaman.java
 *
 * Created on Dec 1, 2011, 2:26:40 PM
 */
package sipus.ui;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sipus.dao.TransaksiPeminjamanDao;
import sipus.dao.svc.DaoService;
import sipus.model.Buku;
import sipus.model.Peminjaman;
import sipus.model.TransaksiPeminjaman;
import sipus.swing.MyTable;
import sipus.table.TableModelPeminjaman;
import sipus.table.render.CurrencyRenderer;
import sipus.table.render.DateRenderer;

/**
 *
 * @author Administrator
 */
public class UIPeminjaman extends javax.swing.JInternalFrame {

    /** Creates new form UIPeminjaman */
    private MainForm mainForm;
    private TableModelPeminjaman modelPeminjaman = new TableModelPeminjaman();
    private int row[] = {60, 100, 100, 250, 150, 150, 150};
    private MyTable table = new MyTable(modelPeminjaman, row);
    private TransaksiPeminjamanDao transaksiPeminjamanDao;
    private String kolom[] = {"No", "Kode Buku", "Judul", "Penulis", "Penerbit", "Kategori"};
    private int kolomWidth[] = {60, 100, 250, 150, 150, 150};
    private DefaultTableModel modelBuku = new DefaultTableModel(kolom, 0);
    private MyTable tableBuku = new MyTable(modelBuku, kolomWidth);
    private UITransaksiPeminjaman uITransaksiPeminjaman = new UITransaksiPeminjaman();

    public UIPeminjaman() {
        initComponents();
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        panelBuku = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        bTutup = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tDataPeminjaman = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        bReload = new javax.swing.JButton();

        panelBuku.setLayout(new java.awt.BorderLayout());
        panelBuku.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });
        jPanel2.add(bTutup);

        panelBuku.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tDataPeminjaman.setFont(new java.awt.Font("Tahoma", 1, 11));
        tDataPeminjaman.setText("Data Peminjaman : ");
        jPanel4.add(tDataPeminjaman);

        panelBuku.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Peminjaman Buku");

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/new.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipus/icon/reload.png"))); // NOI18N
        bReload.setText("Reload");
        bReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(bReload)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(bReload))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        mainForm.showTransaksiPeminjaman();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        // TODO add your handling code here:
        popUp.setVisible(false);
    }//GEN-LAST:event_bTutupActionPerformed

    private void bReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReloadActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_bReloadActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReload;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTutup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBuku;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JLabel tDataPeminjaman;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        transaksiPeminjamanDao = DaoService.getTransaksiPeminjamanDao();
        table.getColumnModel().getColumn(4).setCellRenderer(new DateRenderer());
        table.getColumnModel().getColumn(5).setCellRenderer(new DateRenderer());
        table.getColumnModel().getColumn(6).setCellRenderer(new CurrencyRenderer());

        popUp.setPreferredSize(new Dimension(600, 200));
        popUp.add(panelBuku);

        jScrollPane1.setViewportView(table);
        jScrollPane2.setViewportView(tableBuku);

        table.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.getModifiers() == 16) {
                    getData(modelPeminjaman.getValueAt(table.getSelectedRow(), 1).toString());
                    popUp.setLocation(e.getXOnScreen(), e.getYOnScreen());
                    popUp.setVisible(true);
                }

            }

            private void getData(String kodeTransaksi) {
                for (int i = tableBuku.getRowCount() - 1; i >= 0; i--) {
                    modelBuku.removeRow(i);
                }
                TransaksiPeminjaman peminjaman = new TransaksiPeminjaman();
                peminjaman.setKodeTransaksi(kodeTransaksi);
                tDataPeminjaman.setText("Data Peminjaman : " + modelPeminjaman.getValueAt(table.getSelectedRow(), 3));
                List<Buku> list = transaksiPeminjamanDao.getBukuDipinjam(peminjaman);
                for (Buku buku : list) {
                    String data[] = {"", buku.getKode(), buku.getJudul(), buku.getPenulis(), buku.getPenerbit(), buku.getKategori()};
                    modelBuku.addRow(data);
                }
            }
        });

        uITransaksiPeminjaman.setUIPeminjaman(this);
        reload();
    }

    public void setMainForm(MainForm mainForm) {
        this.mainForm = mainForm;
    }

    public void reload() {
        for (int i = table.getRowCount() - 1; i >= 0; i--) {
            modelPeminjaman.delete(i);
        }
        List<Peminjaman> list = transaksiPeminjamanDao.getAll();
        for (Peminjaman peminjaman : list) {
            peminjaman.setKodeTransaksi(peminjaman.getKodeTransaksi());
            peminjaman.setKodeAnggota(peminjaman.getKodeAnggota());
            peminjaman.setNamaAnggota(peminjaman.getNamaAnggota());
//            dateFormat.format(peminjaman.getTanggalKembali());
            peminjaman.setTanggalPinjam(peminjaman.getTanggalPinjam());
            peminjaman.setTanggalKembali(peminjaman.getTanggalKembali());
            peminjaman.setTotal(peminjaman.getTotal());
            modelPeminjaman.insert(peminjaman);
        }
    }
}
